### ISSUE TITLE
[BUG]  HandshakeFailed when run fossa analyze

### ISSUE THREAD

**Issue by 0exception** [fossas/fossa-cli#1417]
**Describe the bug**
1. i can correctly visit https://fossa.tc.lenovo.com/ from native browser
2. i set my api key correctly

and then i run fossa analyze,  HandshakeFailed, i tried this  Documentation: https://github.com/fossas/fossa-cli/blob/v3.9.13/docs/walkthroughs/ssl-cert.md  ,but It doesn't seem to be working

![image](https://github.com/fossas/fossa-cli/assets/14058021/d1c84227-81e0-44bf-bf5a-0d56ddb6ab0e)

**Comment by csasarak** [comment]
Hello, this should be resolved in versions >= 3.9.15. [Release Notes](https://github.com/fossas/fossa-cli/releases/tag/v3.9.15).

**Comment by xuchenCN** [comment]
@csasarak still occur this issue in `3.9.98`

`SSL_CERT_FILE=/home/fossa/fossa.pem   /home/fossa/fossa analyze --endpoint https://fossa.labs-my.com --fossa-api-key xxxxxxxxxxxxxxxxxx`

```
[ERROR] An issue occurred

  *** Relevant Errors ***

      Error: A socket-level error occurred when accessing the FOSSA API
        HandshakeFailed (Error_Protocol "certificate has unknown CA" UnknownCa)

      These errors are usually related to TLS issues or the host being unreachable.
      Documentation: https://github.com/fossas/fossa-cli/blob/v3.9.38/docs/walkthroughs/ssl-cert.md
      Support: If you believe this to be a defect, please report a bug to FOSSA support at https://support.fossa.com
      Help: For troubleshooting steps with TLS issues, please refer to the provided documentation
      Documentation: https://github.com/fossas/fossa-cli/blob/v3.9.38/README.md#generating-an-api-key
      Help: Ensure that you are using a valid FOSSA_API_KEY. Refer to the provided documentation for guidance on how to generate and retrieve your API key.
```

I confirm that the api key is correct

OS: Rocky 9.2
fossa-cli verision: 3.9.98
