### ISSUE TITLE
Support custom directory path when installing hscli

### ISSUE THREAD

**Issue by yycptt** [fossas/fossa-cli#587]
**Is your feature request related to a problem? Please describe.**
Before this commit https://github.com/fossas/fossa-cli/pull/568, when installing fossa-cli and don't have access to `/usr/local/bin`, we can specify a custom directory. However, now `install.sh` will also try to install https://github.com/fossas/spectrometer and there's no way to specify the directory for the  installation. This means the script will try to install the new package to `/usr/local/bin` which we don't have access to. 

**Describe the solution you'd like**
Probably reuse the directory path specified by `-b` flag to install hscli. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by cnr** [comment]
We just pushed an update to the install script, so hscli install failures shouldn't affect the rest of fossa-cli anymore.

Thanks for opening this!

**Comment by yycptt** [comment]
@cnr Thanks a lot fixing this issue! I really appreciate your quick response. However, I think the current fix doesn't fully resolve our issue. 

When there's no permission to `/usr/local/bin`, two possible situations may occur:
1. The script fails. This will be fixed by your update to the install script.
2. The script blocks, waiting for user to enter the sudo password. Your update doesn't cover this case, but it's exactly what our team encounters right now. 
```
./scripts/buildkite/fossa.sh
--
  | + curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh
  | + bash -s -- -b /var/lib/buildkite-agent/
  | % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
  | Dload  Upload   Total   Spent    Left  Speed
  | 100  9608  100  9608    0     0   170k      0 --:--:-- --:--:-- --:--:--  170k
  | fossas/fossa-cli info checking GitHub for latest tag
  | fossas/fossa-cli info found version: 1.0.24 for v1.0.24/linux/amd64
  | fossas/fossa-cli info installed /var/lib/buildkite-agent//fossa
  | % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
  | Dload  Upload   Total   Spent    Left  Speed
  | 100  9460  100  9460    0     0   167k      0 --:--:-- --:--:-- --:--:--  167k
  | [sudo] password for buildkite-agent:
```

We are using fossa in our buildkite pipeline, so there's no way we can enter the sudo password. Although the build will eventually pass as, I guess, there's a timeout for entering the password, it increases the build time a lot. Previous it only takes around 15s to install fossa and run the analysis, now due to the password and timeout, we need to wait more than 5mins. 

This is not an urgent issue for us as we can definitely wait for 5 mins, but I think the user experience is not good for us. I don't think our team will be the only one affect by this issue, so I want to share our situation here and brought this issue to your attention. Thanks again for your time and taking care of this issue.

**Comment by cnr** [comment]
This will be fixed shortly -- thanks again for following up.

It'll use the same install dir as fossa-cli
